### ISSUE TITLE
h5 file question

### ISSUE THREAD

**Issue by zzzf0104** [VCG/compresso#2]
Can you tell me the function of transforming data into H5 file in the project ？

**Comment by bmatejek** [comment]
Do you mean how do we convert image stacks into h5 files or why do we use h5 files at all?

**Comment by zzzf0104** [comment]
why use h5 files?

**Comment by zzzf0104** [comment]
> Do you mean how do we convert image stacks into h5 files or why do we use h5 files at all?

why do you use h5 files

**Comment by bmatejek** [comment]
Many biomedical volume datasets are stored as h5 files.

**Comment by zzzf0104** [comment]
> Many biomedical volume datasets are stored as h5 files.

Thank you for your reply !
